import { Camera, Alert, Incident, KPIStats, RiskIntelligenceState, DetectionBox } from '../types';

export const initialKPIStats: KPIStats = {
  activeCameras: 12,
  totalCameras: 12,
  peopleDetected: 148,
  activeAlerts: 7,
  highRiskEvents: 3,
  loiteringEvents: 12,
  restrictedAreaEvents: 5,
};

export const mockCameras: Camera[] = [
  {
    id: 'cam-01',
    code: 'CAM-01',
    name: 'Main Gate Access',
    location: 'Exterior North',
    status: 'ONLINE',
    fps: 24,
    resolution: '1920x1080',
    peopleCount: 18,
    riskLevel: 'HIGH',
    lastActive: 'Just now',
  },
  {
    id: 'cam-02',
    code: 'CAM-02',
    name: 'Parking Facility North',
    location: 'Exterior West',
    status: 'ONLINE',
    fps: 23,
    resolution: '1920x1080',
    peopleCount: 31,
    riskLevel: 'MEDIUM',
    lastActive: 'Just now',
  },
  {
    id: 'cam-03',
    code: 'CAM-03',
    name: 'Restricted Storage Zone',
    location: 'Warehouse B',
    status: 'ONLINE',
    fps: 24,
    resolution: '1920x1080',
    peopleCount: 4,
    riskLevel: 'CRITICAL',
    lastActive: 'Just now',
  },
  {
    id: 'cam-04',
    code: 'CAM-04',
    name: 'Building Lobby Entrance',
    location: 'Interior Ground',
    status: 'ONLINE',
    fps: 25,
    resolution: '1920x1080',
    peopleCount: 22,
    riskLevel: 'LOW',
    lastActive: 'Just now',
  },
  {
    id: 'cam-05',
    code: 'CAM-05',
    name: 'Perimeter East Fence',
    location: 'Boundary East',
    status: 'ONLINE',
    fps: 22,
    resolution: '1920x1080',
    peopleCount: 2,
    riskLevel: 'LOW',
    lastActive: '1m ago',
  },
  {
    id: 'cam-06',
    code: 'CAM-06',
    name: 'Perimeter West Fence',
    location: 'Boundary West',
    status: 'ONLINE',
    fps: 24,
    resolution: '1920x1080',
    peopleCount: 1,
    riskLevel: 'MEDIUM',
    lastActive: 'Just now',
  },
  {
    id: 'cam-07',
    code: 'CAM-07',
    name: 'Loading Dock Terminal',
    location: 'Logistics Bay',
    status: 'ONLINE',
    fps: 24,
    resolution: '1920x1080',
    peopleCount: 14,
    riskLevel: 'LOW',
    lastActive: 'Just now',
  },
  {
    id: 'cam-08',
    code: 'CAM-08',
    name: 'Server Vault Corridor',
    location: 'Sector 4 Sublevel',
    status: 'ONLINE',
    fps: 25,
    resolution: '1920x1080',
    peopleCount: 1,
    riskLevel: 'LOW',
    lastActive: 'Just now',
  },
  {
    id: 'cam-09',
    code: 'CAM-09',
    name: 'Emergency Exit Corridor',
    location: 'Sector 2 Interior',
    status: 'ONLINE',
    fps: 24,
    resolution: '1920x1080',
    peopleCount: 3,
    riskLevel: 'LOW',
    lastActive: '2m ago',
  },
  {
    id: 'cam-10',
    code: 'CAM-10',
    name: 'Parking Facility South',
    location: 'Exterior South',
    status: 'ONLINE',
    fps: 21,
    resolution: '1920x1080',
    peopleCount: 27,
    riskLevel: 'LOW',
    lastActive: 'Just now',
  },
  {
    id: 'cam-11',
    code: 'CAM-11',
    name: 'Cafeteria & Lounge',
    location: 'Interior Floor 2',
    status: 'ONLINE',
    fps: 24,
    resolution: '1920x1080',
    peopleCount: 19,
    riskLevel: 'LOW',
    lastActive: 'Just now',
  },
  {
    id: 'cam-12',
    code: 'CAM-12',
    name: 'Rooftop Utility Deck',
    location: 'Roof Access',
    status: 'ONLINE',
    fps: 24,
    resolution: '1920x1080',
    peopleCount: 6,
    riskLevel: 'MEDIUM',
    lastActive: 'Just now',
  },
];

export const mockDetectionsByCamera: Record<string, DetectionBox[]> = {
  'cam-01': [
    {
      id: 'det-1',
      label: 'PERSON #024',
      category: 'PERSON',
      confidence: 0.94,
      x: 22,
      y: 28,
      width: 22,
      height: 60,
      trackId: '#024',
      statusTag: 'TRACKING (4.2s)',
    },
    {
      id: 'det-2',
      label: 'WEAPON: FIREARM',
      category: 'WEAPON',
      confidence: 0.87,
      x: 34,
      y: 50,
      width: 10,
      height: 12,
      statusTag: 'CRITICAL THREAT',
    },
    {
      id: 'det-3',
      label: 'PERSON #031',
      category: 'PERSON',
      confidence: 0.91,
      x: 64,
      y: 35,
      width: 20,
      height: 52,
      trackId: '#031',
      statusTag: 'TRACKING (1.8s)',
    },
    {
      id: 'det-4',
      label: 'SAFE: CELL PHONE',
      category: 'NORMAL_OBJECT',
      confidence: 0.92,
      x: 72,
      y: 48,
      width: 7,
      height: 9,
      statusTag: 'SAFE OBJECT',
    },
  ],
  'cam-02': [
    {
      id: 'det-5',
      label: 'PERSON #019',
      category: 'PERSON',
      confidence: 0.96,
      x: 35,
      y: 25,
      width: 18,
      height: 55,
      trackId: '#019',
      statusTag: 'LOITERING (14.2s)',
    },
    {
      id: 'det-6',
      label: 'SAFE: BACKPACK',
      category: 'NORMAL_OBJECT',
      confidence: 0.95,
      x: 44,
      y: 40,
      width: 12,
      height: 20,
      statusTag: 'SAFE OBJECT',
    },
  ],
  'cam-03': [
    {
      id: 'det-7',
      label: 'PERSON #048',
      category: 'PERSON',
      confidence: 0.95,
      x: 40,
      y: 20,
      width: 24,
      height: 65,
      trackId: '#048',
      statusTag: 'ZONE INTRUDER (8.5s)',
    },
    {
      id: 'det-8',
      label: 'WEAPON: EDGED KNIFE',
      category: 'WEAPON',
      confidence: 0.89,
      x: 52,
      y: 48,
      width: 8,
      height: 14,
      statusTag: 'ARMED INTRUSION',
    },
  ],
  'cam-04': [
    {
      id: 'det-9',
      label: 'PERSON #008',
      category: 'PERSON',
      confidence: 0.93,
      x: 28,
      y: 30,
      width: 19,
      height: 56,
      trackId: '#008',
      statusTag: 'NORMAL',
    },
    {
      id: 'det-10',
      label: 'SAFE: BEVERAGE BOTTLE',
      category: 'NORMAL_OBJECT',
      confidence: 0.94,
      x: 36,
      y: 52,
      width: 6,
      height: 10,
      statusTag: 'SAFE OBJECT',
    },
  ],
};

export const initialRiskState: RiskIntelligenceState = {
  currentScore: 72,
  priorityLevel: 'HIGH',
  primaryThreat: 'WEAPON: CONCEALED FIREARM IDENTIFIED',
  attribution: [
    { factor: 'Weapon Detected (Firearm)', points: 40, description: 'Neural vision detected handgun shape with 87% confidence' },
    { factor: 'Restricted Area Intrusion', points: 20, description: 'Track #024 crossed interior red perimeter' },
    { factor: 'Abnormal Rapid Movement', points: 12, description: 'Centroid velocity calculated at 168 px/s' },
  ],
  totalAttributionScore: 72,
  synergyApplied: false,
  synergyBonus: 0,
};

export const mockAlerts: Alert[] = [
  {
    id: 'alt-01',
    severity: 'HIGH',
    eventType: 'Weapon Detected',
    cameraCode: 'CAM-01',
    cameraName: 'Main Gate Access',
    timestamp: '13:38:14',
    timeAgo: '2 min ago',
    trackId: '#024',
    description: 'Firearm object silhouette confirmed near North checkpoint.',
    acknowledged: false,
  },
  {
    id: 'alt-02',
    severity: 'CRITICAL',
    eventType: 'Armed Zone Intrusion',
    cameraCode: 'CAM-03',
    cameraName: 'Restricted Storage Zone',
    timestamp: '13:35:40',
    timeAgo: '5 min ago',
    trackId: '#048',
    description: 'Track entered secure perimeter holding detected edged blade.',
    acknowledged: false,
  },
  {
    id: 'alt-03',
    severity: 'MEDIUM',
    eventType: 'Suspicious Loitering',
    cameraCode: 'CAM-02',
    cameraName: 'Parking Facility North',
    timestamp: '13:31:02',
    timeAgo: '9 min ago',
    trackId: '#019',
    description: 'Track stationary in vehicle lane for >14 seconds.',
    acknowledged: false,
  },
  {
    id: 'alt-04',
    severity: 'LOW',
    eventType: 'Crowd Threshold Exceeded',
    cameraCode: 'CAM-02',
    cameraName: 'Parking Facility North',
    timestamp: '13:24:18',
    timeAgo: '16 min ago',
    description: 'Occupancy reached 31 individuals exceeding normal lane limit.',
    acknowledged: true,
  },
  {
    id: 'alt-05',
    severity: 'HIGH',
    eventType: 'Rapid Movement / Running',
    cameraCode: 'CAM-06',
    cameraName: 'Perimeter West Fence',
    timestamp: '13:15:22',
    timeAgo: '25 min ago',
    trackId: '#011',
    description: 'Sudden sprint detected moving toward loading terminal.',
    acknowledged: true,
  },
  {
    id: 'alt-06',
    severity: 'MEDIUM',
    eventType: 'Restricted Area Intrusion',
    cameraCode: 'CAM-12',
    cameraName: 'Rooftop Utility Deck',
    timestamp: '12:58:45',
    timeAgo: '41 min ago',
    trackId: '#092',
    description: 'Unauthorized access to HVAC maintenance enclosure.',
    acknowledged: true,
  },
  {
    id: 'alt-07',
    severity: 'LOW',
    eventType: 'Loitering Alert',
    cameraCode: 'CAM-07',
    cameraName: 'Loading Dock Terminal',
    timestamp: '12:44:10',
    timeAgo: '55 min ago',
    trackId: '#033',
    description: 'Dwell time exceeded 12s in forklift staging zone.',
    acknowledged: true,
  },
];

export const mockIncidents: Incident[] = [
  {
    id: 'INC-1042',
    timestamp: '13:38:14',
    cameraCode: 'CAM-01',
    cameraName: 'Main Gate Access',
    eventType: 'Weapon Detected',
    trackId: '#024',
    riskScore: 72,
    severity: 'HIGH',
    status: 'UNDER_REVIEW',
    snapshotUrl: '/sentra_logo.jpg',
    breakdown: { 'Weapon (Firearm)': 40, 'Restricted Area': 20, 'Rapid Movement': 12 },
    events: ['FIREARM CONFIRMED', 'CROSS-CHECK COCO NORMAL ITEM', 'ZONE BREACH DETECTED'],
  },
  {
    id: 'INC-1041',
    timestamp: '13:35:40',
    cameraCode: 'CAM-03',
    cameraName: 'Restricted Storage Zone',
    eventType: 'Armed Zone Intrusion',
    trackId: '#048',
    riskScore: 89,
    severity: 'CRITICAL',
    status: 'UNDER_REVIEW',
    snapshotUrl: '/sentra_logo.jpg',
    breakdown: { 'Weapon (Knife)': 35, 'Restricted Area': 30, 'Armed Synergy': 24 },
    events: ['EDGED WEAPON', 'ZONE BREACH DETECTED', 'ARMED SYNERGY MULTIPLIER'],
  },
  {
    id: 'INC-1040',
    timestamp: '13:31:02',
    cameraCode: 'CAM-02',
    cameraName: 'Parking Facility North',
    eventType: 'Suspicious Loitering',
    trackId: '#019',
    riskScore: 45,
    severity: 'MEDIUM',
    status: 'RESOLVED',
    snapshotUrl: '/sentra_logo.jpg',
    breakdown: { 'Loitering (>10s)': 25, 'Crowd Proximity': 20 },
    events: ['LOITERING TIMER TRIGGER', 'SAFE OBJECT (BACKPACK) VERIFIED'],
  },
  {
    id: 'INC-1039',
    timestamp: '13:15:22',
    cameraCode: 'CAM-06',
    cameraName: 'Perimeter West Fence',
    eventType: 'Rapid Running',
    trackId: '#011',
    riskScore: 62,
    severity: 'HIGH',
    status: 'RESOLVED',
    snapshotUrl: '/sentra_logo.jpg',
    breakdown: { 'Rapid Movement': 30, 'Perimeter Proximity': 32 },
    events: ['VELOCITY >150px/s', 'PERIMETER FENCE ALERT'],
  },
  {
    id: 'INC-1038',
    timestamp: '12:58:45',
    cameraCode: 'CAM-12',
    cameraName: 'Rooftop Utility Deck',
    eventType: 'Restricted Intrusion',
    trackId: '#092',
    riskScore: 50,
    severity: 'MEDIUM',
    status: 'RESOLVED',
    snapshotUrl: '/sentra_logo.jpg',
    breakdown: { 'Intrusion': 35, 'Time of Day Penalty': 15 },
    events: ['POINT-IN-POLYGON POSITIVE', 'UNAUTHORIZED ROOF ENTRY'],
  },
  {
    id: 'INC-1037',
    timestamp: '11:20:19',
    cameraCode: 'CAM-01',
    cameraName: 'Main Gate Access',
    eventType: 'Crowd Surge',
    trackId: '#CROWD',
    riskScore: 35,
    severity: 'LOW',
    status: 'RESOLVED',
    snapshotUrl: '/sentra_logo.jpg',
    breakdown: { 'Crowd Limit': 25, 'Gate Congestion': 10 },
    events: ['OCCUPANCY COUNT > 15', 'AUTOMATED GATE EXTENSION'],
  },
];

export const mockAnalytics = {
  hourlyEvents: [
    { hour: '08:00', weapons: 0, intrusion: 1, loitering: 2, crowd: 0 },
    { hour: '09:00', weapons: 0, intrusion: 2, loitering: 4, crowd: 3 },
    { hour: '10:00', weapons: 1, intrusion: 1, loitering: 3, crowd: 2 },
    { hour: '11:00', weapons: 0, intrusion: 3, loitering: 5, crowd: 4 },
    { hour: '12:00', weapons: 0, intrusion: 1, loitering: 6, crowd: 5 },
    { hour: '13:00', weapons: 2, intrusion: 4, loitering: 3, crowd: 1 },
  ],
  riskDistribution: [
    { name: 'Low Priority (0-29)', count: 48, fill: '#10b981' },
    { name: 'Medium Priority (30-59)', count: 24, fill: '#eab308' },
    { name: 'High Priority (60-79)', count: 12, fill: '#f97316' },
    { name: 'Critical Priority (80-100)', count: 4, fill: '#ef4444' },
  ],
  categoryBreakdown: [
    { category: 'Weapon Detection', count: 7, percentage: 15 },
    { category: 'Restricted Intrusion', count: 19, percentage: 40 },
    { category: 'Suspicious Loitering', count: 12, percentage: 25 },
    { category: 'Crowd Density Exceeded', count: 6, percentage: 12 },
    { category: 'Abnormal Movement', count: 4, percentage: 8 },
  ],
};
